name = "argamak"
version = "0.4.0-dev"
description = "A tensor library for the Gleam programming language"
licences = ["Apache-2.0"]

[repository]
repo = "argamak"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_stdlib = "~> 0.23"
nx = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 0.7"
rad = "~> 0.1"

[rad]
targets = ["erlang", "javascript"]

[[rad.formatters]]
name = "elixir"
check = [
  "sh",
  "-c",
  "mix format --check-formatted && echo -n 'Checked all files in `src` and `test`'",
]
run = [
  "sh",
  "-c",
  "mix format && echo -n 'Formatted all files in `src` and `test`'",
]

[[rad.formatters]]
name = "javascript"
check = ["rome", "ci", "--indent-style=space", "src", "test"]
run = ["rome", "format", "--indent-style=space", "--write", "src", "test"]

[[rad.tasks]]
path = ["init"]
run = ["npm", "install"]
shortdoc = "Initialize argamak"
