name = "argamak"
version = "1.0.0-dev"
description = "A tensor library for the Gleam programming language"
licences = ["Apache-2.0"]
gleam = ">= 0.33.0"

[repository]
repo = "argamak"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_stdlib = "~> 0.34"
nx = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 1.0"
rad = "~> 1.0"

[rad]
targets = ["erlang", "javascript"]

[[rad.formatters]]
name = "elixir"
check = [
  "sh",
  "-c",
  "mix format --check-formatted && echo -n 'Checked all files in `src` and `test`'",
]
run = [
  "sh",
  "-c",
  "mix format && echo -n 'Formatted all files in `src` and `test`'",
]

[[rad.formatters]]
name = "javascript"
check = ["deno", "fmt", "--check"]
run = ["deno", "fmt"]

[[rad.tasks]]
path = ["init"]
run = ["npm", "ci"]
shortdoc = "Initialize argamak"
