name: CI

on:
  push:
    branches:
      - main
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          rebar3-version: "3"
          elixir-version: "1.14"
          gleam-version: "0.30"

      - id: cache-gleam
        uses: actions/cache@v3
        with:
          path: build/packages
          key: ${{ runner.os }}-gleam-${{ hashFiles('manifest.toml') }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - id: cache-deno
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - id: cache-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - run: echo "$PWD/build/packages/rad/priv" >> $GITHUB_PATH

      - if: ${{ !steps.cache-gleam.outputs.cache-hit }}
        run: gleam deps download

      - if: ${{ !steps.cache-node.outputs.cache-hit }}
        run: rad init

      - run: rad format --check

      - run: rad test
